webhook: 'https://discord.com/api/webhooks/.../...'
websites:
  - URL: 'https://www.okdo.com/de/p/raspberry-pi-4-model-b-board-mit-2gb-lpddr4-sdram/'
    name: 'okdo.com'
    no_stock_indicator: '<span class="c-stock-level c-stock-level--low">Ausverkauft</span>'
    interval: 5000
  - URL: 'https://www.berrybase.de/detail/index/sArticle/5915'
    name: 'berrybase.de'
    no_stock_indicator: 'Dieser Artikel steht derzeit nicht zur Verfügung!'
    interval: 5000
